Repository Donut-Mod-Team/donut-mod, pull requests merged in 2021-11, with the labels that each got.

#70 DMT-53 Merge labels position to dev
  src/labels.js
  src/renderer.js
Labels: future

#73 Add default center text values
  src/donutState.js
  src/renderer.js
  src/static/index.html
  src/static/main.css
Labels: enhancement

#75 DMT-79 Merge CI updates to dev
  .babelrc
  .eslintrc.json
  .github/workflows/cypress.yml
  .github/workflows/node.js.yml
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/testRender.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress_ci.sh
  jest.config.js
  package.json
  test/unit/utility.test.js
Labels: testing, ci-pipeline

#78 DMT-82 Fix selection of sectors despite being marked
  src/marker.js
  src/renderer.js
Labels: bug

#77 DMT-65 Add center text styling
  src/donutState.js
  src/renderer.js
  src/static/main.css
Labels: enhancement

#85 DMT-81 Update documentation
  README.md
  documentation/architecture.md
  documentation/ci-cd.md
  documentation/ci_cd.md
  documentation/diagrams/system_architecture_v3.png
  documentation/requirements.md
  documentation/user_guide.md
Labels: documentation

#86 DMT-86 Fix settings icon visibility
  src/popout.js
  src/static/main.css
Labels: bug

#87 DMT-84 Format values
  src/donutState.js
  src/renderer.js
Labels: bug

#88 DMT-87 Unit tests
  src/utility.js
  test/unit/utility.test.js
Labels: testing

#89 DMT-54 Add semi circle functionality
  src/centerText.js
  src/hoverer.js
  src/labels.js
  src/main.js
  src/popout.js
  src/renderer.js
  src/resources.js
  src/static/main.css
  src/static/mod-manifest.json
Labels: enhancement

#91 DMT-89 Fix formatting center value
  src/centerText.js
  src/donutState.js
  src/renderer.js
  src/utility.js
Labels: bug

#92 DMT-43 Update documentation
  README.md
  documentation/UI_and_UX_design.md
  documentation/architecture.md
  documentation/diagrams/system_architecture_v4.png
  documentation/user_guide.md
  documentation/ux-prototypes/Prototype V.1.0. Donut Chart.PNG
Labels: documentation

#94 DMT-90 Fix center-text positioning on semi-circle
  src/centerText.js
  src/renderer.js
Labels: bug

#95 DMT-87 Add unit test for formatted sum method
  test/unit/utility.test.js
Labels: testing

#96 DMT-85 Resize donut when labels outside
  src/labels.js
  src/main.js
  src/popout.js
  src/renderer.js
  src/resources.js
  src/utility.js
Labels: enhancement

#97 Merge unit tests to dev
  src/utility.js
  test/unit/utility.test.js
Labels: testing

#98 DMT-92 Fix labels text visibility options in popout setting menu
  src/labels.js
Labels: bug

#99 DMT-91 Fix multiple marking rectangles
  package-lock.json
  src/marker.js
Labels: bug

#100 DMT-68 Fix hover highlight
  src/hoverer.js
  src/renderer.js
  src/resources.js
  src/static/index.html
Labels: bug

#101 DMT-93 Merge bugfix for marking on semi-circle to dev
  src/marker.js
  src/renderer.js
  src/resources.js
Labels: bug
