Repository Donut-Mod-Team/donut-mod, pull requests merged in 2021-09, with the labels that each got.

#6 DMT-5 Integrate spotfire api and documentation
  .gitignore
  documentation/UI_and_UX_design.md
  documentation/user_guide.md
  package-lock.json
  package.json
  spotfire/mod-schema.json
  spotfire/spotfire-api-1-2.d.ts
  src/icon.svg
  src/index.html
  src/main.css
  src/main.js
  src/mod-manifest.json
Labels: Sprint #1

#7 DMT-23 Create build related CI pipeline
  .github/workflows/node.js.yml
Labels: Sprint #1

#8 DMT-21 Use case diagram
  README.md
  documentation/architecture.md
  documentation/diagrams/Use_Case_Diagram_v1.png
  documentation/requirements.md
Labels: Sprint #1

#10 DMT-19 Add CI/CD related references to the documentation
  README.md
  documentation/ci-cd.md
Labels: documentation, Sprint #1

#11 DMT-27 Add custom mod-icon for Donut-Chart
  src/icon.svg
Labels: Sprint #1

#12 DMT-18 Add high level architectural diagram
  documentation/architecture.md
  documentation/diagrams/system_architecture_v1.png
Labels: documentation

#13 DMT-15 Mod icon update
  src/icon.svg
Labels: Sprint #1

#14 Add license to the project
  LICENSE
Labels: documentation

#15 DMT-29 Add static code analysis tools
  package-lock.json
  package.json
  src/donutChart.js
  src/main.css
  src/main.js
  webpack.config.js
Labels: Sprint #2

#16 DMT-28 Merge code-refactoring to sprint-1
  .eslintrc.json
  .prettierignore
  documentation/user_guide.md
  package-lock.json
  package.json
  src/donutChart.js
  src/icon.svg
  src/index.html
  src/main.css
  src/main.js
  src/mod-manifest.json
  tsconfig.json
  webpack.config.js
Labels: Sprint #1

#17 Merge sprint-1 to main
  .eslintrc.json
  .github/workflows/node.js.yml
  .gitignore
  .prettierignore
  LICENSE
  README.md
  documentation/UI_and_UX_design.md
  documentation/architecture.md
  documentation/ci-cd.md
  documentation/diagrams/Use_Case_Diagram_v1.png
  documentation/diagrams/system_architecture_v1.png
  documentation/requirements.md
  documentation/requirments.md
  documentation/user_guide.md
  documentation/ux-prototypes/Prototype V.1.0. Donut Chart.PNG
  package-lock.json
  package.json
  prettier.config.js
  spotfire/mod-schema.json
  spotfire/spotfire-api-1-2.d.ts
  src/donutChart.js
  src/icon.svg
  src/index.html
  src/main.css
  src/main.js
  src/mod-manifest.json
  tsconfig.json
  webpack.config.js
Labels: Sprint #1

#19 Merge code-refactoring to sprint-2
  src/donutState.js
  src/main.js
  src/renderer.js
  src/static/icon.svg
  src/static/index.html
  src/static/main.css
  src/static/mod-manifest.json
  webpack.config.js
Labels: Sprint #2
