Repository Donut-Mod-Team/donut-mod, pull requests merged in 2021-12, with the labels that each got.

#104 DMT-95 Fix issue with label anchoring for semi-circle
  src/labels.js
Labels: bug

#102 DMT-89 Update formatting of labels and center value
  package-lock.json
  src/centerText.js
  src/donutState.js
  src/utility.js
  test/unit/utility.test.js
Labels: bug

#105 DMT-94 Fix empty sectors
  src/donutState.js
Labels: bug

#106 Merge dev into main
  README.md
  documentation/UI_and_UX_design.md
  documentation/architecture.md
  documentation/diagrams/Tibco_UG_Image.PNG
  documentation/diagrams/system_architecture_v4.png
  documentation/tibco_user_guide.md
  documentation/user_guide.md
  documentation/ux-prototypes/Prototype V.1.0. Donut Chart.PNG
  package-lock.json
  src/centerText.js
  src/donutState.js
  src/hoverer.js
  src/labels.js
  src/main.js
  src/marker.js
  src/popout.js
  src/renderer.js
  src/resources.js
  src/static/index.html
  src/utility.js
  test/unit/utility.test.js
Labels: bug, documentation, enhancement, testing

#107 DMT-96 Hotfix rendering bugs
  src/donutState.js
  src/renderer.js
Labels: bug

#108 DMT-97 Update rendering labels
  src/donutState.js
  src/labels.js
  src/static/main.css
Labels: bug

#116 DMT-102 Update label's text
  src/donutState.js
Labels: enhancement

#120 DMT-88 Cypress removal
  .github/workflows/cypress.yml
  README.md
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/testRender.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress_ci.sh
  documentation/ci_cd.md
  documentation/user_guide.md
  jest.config.js
  package.json
Labels: testing

#115 DMT-98 Fix empty data error
  src/main.js
  src/resources.js
Labels: bug

#118 DMT-103 Update center text's positioning in semi-circle mode
  src/centerText.js
  src/resources.js
Labels: enhancement

#117 DMT-105 Multiple settings
  src/popout.js
Labels: enhancement

#121 Merge codebase-refactoring to dev
  src/centerText.js
  src/donutState.js
  src/labels.js
  src/main.js
  src/renderer.js
  src/resources.js
  src/utility.js
  test/unit/utility.test.js
Labels: bug, enhancement

#123 Add class diagram
  documentation/architecture.md
  documentation/diagrams/system_class_diagram_v1.png
Labels: documentation

#124 Update the architecture diagram
  documentation/architecture.md
  documentation/diagrams/system_architecture_v5.png
Labels: documentation

#125 Add code quality actions
  .github/workflows/codeql-config.yml
  README.md
Labels: ci-pipeline

#122 Update use case diagram
  documentation/architecture.md
  documentation/diagrams/Use_Case_Diagram_v1.png
  documentation/diagrams/use_case_diagram.v2.png
Labels: documentation

#127 Merge dev into main
  .github/workflows/codeql-config.yml
  .github/workflows/cypress.yml
  README.md
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/testRender.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress_ci.sh
  documentation/architecture.md
  documentation/ci_cd.md
  documentation/diagrams/Use_Case_Diagram_v1.png
  documentation/diagrams/system_architecture_v5.png
  documentation/diagrams/system_class_diagram_v1.png
  documentation/diagrams/use_case_diagram.v2.png
  documentation/requirements.md
  documentation/tibco_user_guide.md
  documentation/user_guide.md
  jest.config.js
  package.json
  src/centerText.js
  src/donutState.js
  src/labels.js
  src/main.js
  src/popout.js
  src/renderer.js
  src/resources.js
  src/static/main.css
  src/utility.js
  test/unit/utility.test.js
Labels: bug, documentation, enhancement, testing, ci-pipeline

#131 Merge hotfix-duplicate-id to main
  src/donutState.js
  src/hoverer.js
  src/labels.js
  src/renderer.js
  src/static/mod-manifest.json
Labels: bug
