Repository Donut-Mod-Team/donut-mod, pull requests merged in 2021-10, with the labels that each got.

#21 DMT-34 Add leaf data to tooltip
  src/donutState.js
Labels: Sprint #2

#20 DMT-10 Data marking
  documentation/user_guide.md
  src/donutState.js
  src/marker.js
  src/renderer.js
  src/static/main.css
Labels: Sprint #2

#22 DMT-30 Add labels to the partitions of the visualization
  src/donutState.js
  src/renderer.js
  src/static/index.html
  src/static/main.css
Labels: Sprint #2

#23 Sprint 2
  .gitignore
  documentation/user_guide.md
  package-lock.json
  package.json
  src/donutChart.js
  src/donutState.js
  src/main.css
  src/main.js
  src/marker.js
  src/renderer.js
  src/static/icon.svg
  src/static/index.html
  src/static/main.css
  src/static/mod-manifest.json
  webpack.config.js
Labels: Sprint #2

#24 DMT-35 implement sector-hovering stroke
  src/renderer.js
Labels: Sprint #3

#25 DMT-42 Refactor and add tooltip ratio
  src/donutState.js
  src/renderer.js
Labels: Sprint #3

#27 DMT-36 Add center text
  src/donutState.js
  src/renderer.js
  src/static/index.html
  src/static/main.css
  src/utility.js
Labels: Sprint #3

#33 Refactor styles
  src/donutState.js
  src/renderer.js
Labels: Sprint #3

#35 DMT-48 Fix issue with rendering when changing data
  src/renderer.js
Labels: Sprint #3

#36 DMT-46 Update padding
  src/renderer.js
Labels: Sprint #3

#41 DMT-51 Fix animation flicker
  src/renderer.js
Labels: bug
